---
title: "A dataset to study pragmatic language code"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## A dataset to study pragmatic language, and its cognitive processes as theory of mind

Data and code for the paper: 
https://doi.org/10.3389/fnhum.2021.666210

Please let us know if something in the code is incomplete, files are missing or you have any issues:
In issues section or by mail: jalil.rasgadoto@gmail.com

## About

- The present dataset includes structural brain images, as well as resting state functional connectivity from six different projects of pragmatic language and its underlying cognitive processes in young neurotypical Mexican participants.
- In Workflow tab we show the workflow for the analysis presented in the paper.

## Authors

Jalil Rasgado-Toledo, Fernando Lizcano-Cortés, Víctor Enrique Olalde-Mathieu, Giovanna Licea-Haquet, Miguel Angel Zamora-Ursulo, Magda Giordano and Azalea Reyes-Aguilar
